// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	ID       string  `json:"Id"`
	Name     *string `json:"Name"`
	Email    *string `json:"Email"`
	Password *string `json:"Password"`
	Cpf      *string `json:"CPF"`
	Phone    *string `json:"Phone"`
}

type Fidelity struct {
	ID       string  `json:"Id"`
	ClientID *string `json:"ClientId"`
	Score    *int    `json:"Score"`
}

type NewClient struct {
	Name     string `json:"Name"`
	Email    string `json:"Email"`
	Password string `json:"Password"`
	Cpf      string `json:"CPF"`
	Phone    string `json:"Phone"`
}

type NewFidelity struct {
	ClientID string `json:"ClientId"`
	Score    int    `json:"Score"`
}

type NewOrder struct {
	MarketplaceUserID string  `json:"marketplace_user_id"`
	ClientID          string  `json:"ClientId"`
	TableID           string  `json:"TableId"`
	TotalPrice        float64 `json:"TotalPrice"`
}

type NewProduct struct {
	MarketplaceID string  `json:"MarketplaceId"`
	Name          string  `json:"Name"`
	Description   string  `json:"Description"`
	Price         float64 `json:"Price"`
}

type NewTable struct {
	Number int    `json:"Number"`
	Qrcode string `json:"Qrcode"`
}

type NewUser struct {
	Name        string        `json:"Name"`
	Description string        `json:"Description"`
	Cnpj        string        `json:"CNPJ"`
	Email       string        `json:"Email"`
	Password    string        `json:"Password"`
	Image       string        `json:"Image"`
	Superadmin  bool          `json:"Superadmin"`
	Admin       bool          `json:"Admin"`
	Products    []*NewProduct `json:"Products"`
	Tables      []*NewTable   `json:"Tables"`
}

type Order struct {
	ID                int        `json:"id"`
	MarketplaceUserID string     `json:"marketplace_user_id"`
	ClientID          string     `json:"client_id"`
	TableID           string     `json:"table_id"`
	TotalPrice        float64    `json:"total_price"`
	Products          []*Product `json:"products"`
}

type Product struct {
	ID            int     `json:"Id"`
	MarketplaceID string  `json:"MarketplaceId"`
	Name          string  `json:"Name"`
	Description   string  `json:"Description"`
	Price         float64 `json:"Price"`
	Order         *Order  `json:"order"`
}

type Table struct {
	ID     string  `json:"Id"`
	Number *int    `json:"Number"`
	Qrcode *string `json:"Qrcode"`
}

type User struct {
	ID          string     `json:"Id"`
	Name        *string    `json:"Name"`
	Description *string    `json:"Description"`
	Cnpj        *string    `json:"CNPJ"`
	Email       *string    `json:"Email"`
	Password    *string    `json:"Password"`
	Image       *string    `json:"Image"`
	Superadmin  *bool      `json:"Superadmin"`
	Admin       *bool      `json:"Admin"`
	Products    []*Product `json:"Products"`
	Tables      []*Table   `json:"Tables"`
}
