// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Marketplaces struct {
	ID          string      `gorm:"primary_key" json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Cnpj        string      `json:"cnpj"`
	Email       string      `json:"email"`
	Password    string      `json:"password"`
	Version     string      `json:"version"`
	Products    []*Products `gorm:"foreignKey:marketplace_id" json:"products"`
	Tables      []*Tables   `gorm:"foreignKey:marketplace_id" json:"tables"`
}

type Tables struct {
	ID            string `json:"id"`
	Number        int    `json:"number"`
	Qrcode        string `json:"qrcode"`
	MarketplaceID string `json:"marketplace_id"`
}

type Products struct {
	ID            string   `gorm:"primary_key" json:"id"`
	Name          string   `json:"name"`
	Description   string   `json:"description"`
	Price         float64  `json:"price"`
	Images        []string `gorm:"type:text[]" json:"images"`
	MarketplaceID string   `json:"marketplace_id"`
}

type NewMarketplace struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Cnpj        string `json:"cnpj"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Version     string `json:"version"`
}

type NewProduct struct {
	ID            string   `json:"id"`
	MarketplaceID string   `json:"marketplace_id"`
	Name          string   `json:"name"`
	Description   string   `json:"description"`
	Price         float64  `json:"price"`
	Images        []string `json:"images"`
}


